name: CI

on:
  push:
    branches:
      - "**"
      - "!dependabot/**"
    tags:
      # semver tags
      - 'v[0-9]+\.[0-9]+\.[0-9]+-?**'
  pull_request: {}

jobs:
  tools:
    # Synthetic job to host config anchors referenced by other jobs.
    # Running this job does no meaningful work, but would pass.
    name: Build and cache tools
    runs-on: ${{ matrix.os }}
    if: false
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-24.04
          - os: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
          cache-dependency-path: "**/*.sum"
      - parallel:
          - &install-controller-gen
            name: Install controller-gen
            uses: reconcilerio/go-install-action@v1
            with:
              package: sigs.k8s.io/controller-tools/cmd/controller-gen
              working-directory: hack/controller-gen
              download-url-template: https://github.com/kubernetes-sigs/controller-tools/releases/download/${version}/controller-gen-${os}-${arch}
              output-path-env: CONTROLLER_GEN
              toolchain: auto
          - &install-diegen
            name: Install diegen
            uses: reconcilerio/go-install-action@v1
            with:
              package: reconciler.io/dies/diegen
              working-directory: hack/diegen
              download-url-template: https://github.com/reconcilerio/dies/releases/download/${version}/diegen-${os}-${arch}
              output-path-env: DIEGEN
              toolchain: auto
          - &install-goimports
            name: Install goimports
            uses: reconcilerio/go-install-action@v1
            with:
              package: golang.org/x/tools/cmd/goimports
              working-directory: hack/goimports
              output-path-env: GOIMPORTS
              toolchain: auto
          - &install-golangci-lint
            name: Install golangci-lint
            uses: reconcilerio/go-install-action@v1
            with:
              package: github.com/golangci/golangci-lint/v2/cmd/golangci-lint
              working-directory: hack/golangci-lint
              download-url-template: https://github.com/golangci/golangci-lint/releases/download/${version}/golangci-lint-${version:1}-${os}-${arch}.tar.gz
              download-path-within-archive: golangci-lint-${version:1}-${os}-${arch}/golangci-lint
              output-path-env: GOLANGCI_LINT
              toolchain: auto
          - &install-imgpkg
            name: Install imgpkg
            uses: reconcilerio/go-install-action@v1
            with:
              package: carvel.dev/imgpkg/cmd/imgpkg
              working-directory: hack/imgpkg
              download-url-template: https://github.com/carvel-dev/imgpkg/releases/download/${version}/imgpkg-${os}-${arch}
              output-path-env: IMGPKG
              toolchain: auto
          - &install-kapp
            name: Install kapp
            uses: reconcilerio/go-install-action@v1
            with:
              package: carvel.dev/kapp/cmd/kapp
              working-directory: hack/kapp
              download-url-template: https://github.com/carvel-dev/kapp/releases/download/${version}/kapp-${os}-${arch}
              output-path-env: KAPP
              toolchain: auto
          - &install-kbld
            name: Install kbld
            uses: reconcilerio/go-install-action@v1
            with:
              package: carvel.dev/kbld/cmd/kbld
              working-directory: hack/kbld
              download-url-template: https://github.com/carvel-dev/kbld/releases/download/${version}/kbld-${os}-${arch}
              output-path-env: KBLD
              toolchain: auto
          - &install-ko
            name: Install ko
            uses: reconcilerio/go-install-action@v1
            with:
              package: github.com/google/ko
              working-directory: hack/ko
              download-url-template: https://github.com/ko-build/ko/releases/download/${version}/ko_${version:1}_${os^}_${arch/amd64/x86_64}.tar.gz
              download-path-within-archive: ko
              output-path-env: KO
              toolchain: auto
          - &install-kustomize
            name: Install kustomize
            uses: reconcilerio/go-install-action@v1
            with:
              package: sigs.k8s.io/kustomize/kustomize/v4
              working-directory: hack/kustomize
              download-url-template: https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2F${version}/kustomize_${version}_${os}_${arch}.tar.gz
              download-path-within-archive: kustomize
              output-path-env: KUSTOMIZE
              toolchain: auto
          - &install-stern
            name: Install stern
            uses: reconcilerio/go-install-action@v1
            with:
              package: github.com/stern/stern
              working-directory: hack/stern
              download-url-template: https://github.com/stern/stern/releases/download/${version}/stern_${version:1}_${os}_${arch}.tar.gz
              download-path-within-archive: stern
              output-path-env: STERN
              toolchain: auto
          - &install-yq
            name: Install yq
            uses: reconcilerio/go-install-action@v1
            with:
              package: github.com/mikefarah/yq/v4
              working-directory: hack/yq
              download-url-template: https://github.com/mikefarah/yq/releases/download/${version}/yq_${os}_${arch}
              output-path-env: YQ
              toolchain: auto
          - &install-ytt
            name: Install ytt
            uses: reconcilerio/go-install-action@v1
            with:
              package: carvel.dev/ytt/cmd/ytt
              working-directory: hack/ytt
              download-url-template: https://github.com/carvel-dev/ytt/releases/download/${version}/ytt-${os}-${arch}
              output-path-env: YTT
              toolchain: auto

  unit:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
          cache-dependency-path: "**/*.sum"
      - uses: actions-rust-lang/setup-rust-toolchain@v2
      - name: Install cargo binstall
        uses: cargo-bins/cargo-binstall@main
      - parallel:
          - name: Install cargo component
            run: cargo binstall --force cargo-component
          - name: Install wasm-tools
            run: cargo binstall --force wasm-tools
          - name: Install wkg
            run: cargo binstall --force wkg
          - *install-controller-gen
          - *install-diegen
          - *install-goimports
          - *install-golangci-lint
          - *install-kustomize
          - *install-yq
      - name: Test
        run: make test
      - name: Lint
        run: make lint
      - name: Report coverage
        uses: codecov/codecov-action@v7
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: Disallow generated drift
        run: |
          set -o errexit
          set -o nounset
          set -o pipefail

          git diff --exit-code .

  stage:
    name: Stage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
          cache-dependency-path: "**/*.sum"
      - uses: actions-rust-lang/setup-rust-toolchain@v2
      - name: Install cargo binstall
        uses: cargo-bins/cargo-binstall@main
      - parallel:
          - name: Install cargo component
            run: cargo binstall --force cargo-component
          - name: Install wasm-tools
            run: cargo binstall --force wasm-tools
          - name: Install wkg
            run: cargo binstall --force wkg
          - *install-imgpkg
          - *install-kbld
          - *install-ko
      - name: Start registry
        id: registry
        uses: reconcilerio/registry@v1
      - name: Build all platforms for tags
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo "KO_PLATFORMS=all" >> $GITHUB_ENV
      - name: Build
        run: |
          set -o errexit
          set -o nounset
          set -o pipefail

          scratch=$(mktemp -d -t bundle.XXXX)
          mkdir -p "${scratch}/.imgpkg"
          mkdir -p "${scratch}/config"

          cp LICENSE "${scratch}/LICENSE"
          cp -R config/kapp "${scratch}/kapp"

          echo "##[group]Build components"
            make components
          echo "##[endgroup]"

          echo "##[group]Build"
            cat hack/boilerplate.yaml.txt > "${scratch}/config/reconcilerio-wa8s.yaml"
            ${KO} resolve --platform ${KO_PLATFORMS} -f config/wa8s.yaml >> "${scratch}/config/reconcilerio-wa8s.yaml"
            
            cat hack/boilerplate.yaml.txt > "${scratch}/config/reconcilerio-wa8s-knative.yaml"
            ${KO} resolve --platform ${KO_PLATFORMS} -f config/wa8s-knative.yaml >> "${scratch}/config/reconcilerio-wa8s-knative.yaml"
            
            cat hack/boilerplate.yaml.txt > "${scratch}/config/reconcilerio-wa8s-services.yaml"
            ${KO} resolve --platform ${KO_PLATFORMS} -f config/wa8s-services.yaml >> "${scratch}/config/reconcilerio-wa8s-services.yaml"

            ${KBLD} --imgpkg-lock-output "${scratch}/.imgpkg/images.yml" \
              -f "${scratch}/config/reconcilerio-wa8s.yaml" \
              -f "${scratch}/config/reconcilerio-wa8s-knative.yaml" \
              -f "${scratch}/config/reconcilerio-wa8s-services.yaml" \
              > /dev/null
          echo "##[endgroup]"

          echo "##[group]Create bundle"
            bundle="${{ steps.registry.outputs.registry }}/bundle"
            ${IMGPKG} push -f "${scratch}" -b "${bundle}"
            ${IMGPKG} copy -b "${bundle}" --to-tar reconcilerio-wa8s-bundle.tar
          echo "##[endgroup]"
        env:
          KO_DOCKER_REPO: ${{ steps.registry.outputs.registry }}/wa8s
          KO_PLATFORMS: linux/amd64,linux/arm64
      - uses: actions/upload-artifact@v7
        with:
          name: reconcilerio-wa8s-bundle.tar
          path: reconcilerio-wa8s-bundle.tar
          retention-days: 7

  acceptance:
    name: Acceptance Test
    needs: stage
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - kubernetes: v1.36
            os: ubuntu-24.04
          - kubernetes: v1.36
            os: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
          cache-dependency-path: "**/*.sum"
      - parallel:
          - *install-imgpkg
          - *install-kapp
          - *install-kbld
          - *install-stern
          - *install-ytt
      - name: OCI registry
        id: registry
        uses: reconcilerio/registry@v1
      - name: kind cluster
        uses: reconcilerio/kind@v1
        with:
          kubernetes-version: ${{ matrix.kubernetes }}
          cloud-provider-kind-version: auto
          registry: ${{ steps.registry.outputs.registry }}
          registry-ca: ${{ steps.registry.outputs.tls-ca }}
      - name: Download staged bundle
        uses: actions/download-artifact@v8
        with:
          name: reconcilerio-wa8s-bundle.tar
      - name: Relocate bundle
        run: |
          set -o errexit
          set -o nounset
          set -o pipefail

          bundle="${{ steps.registry.outputs.registry }}/bundle"

          ${IMGPKG} copy --tar reconcilerio-wa8s-bundle.tar --to-repo "${bundle}"
          mkdir -p bundle
          ${IMGPKG} pull -b "${bundle}" -o bundle
      - name: Deploy
        run: |
          set -o errexit
          set -o nounset
          set -o pipefail

          echo "##[group]Create apps namespace"
            kubectl create ns apps
          echo "##[endgroup]"

          echo "##[group]Deploy cert-manager"
            ${KAPP} deploy -a cert-manager -n apps --wait-timeout 5m -y \
              -f https://github.com/cert-manager/cert-manager/releases/download/v1.19.2/cert-manager.yaml
          echo "##[endgroup]"

          echo "##[group]Deploy knative-serving"
            ${KAPP} deploy -a knative-serving -n apps --wait-timeout 5m -y \
              -f <( \
                ${YTT} \
                  --data-value external-domain=knative.local \
                  --data-value ingress-class=kourier.ingress.networking.knative.dev \
                  -f config/overlays/knative-domain.yaml \
                  -f config/overlays/knative-ingress-class.yaml \
                  -f https://github.com/knative/serving/releases/download/knative-v1.21.2/serving-crds.yaml \
                  -f https://github.com/knative/serving/releases/download/knative-v1.21.2/serving-core.yaml \
                  -f https://github.com/knative-extensions/net-kourier/releases/download/knative-v1.21.0/kourier.yaml \
              )
          echo "##[endgroup]"

          echo "##[group]Deploy reconcilerio-ducks"
            ${KAPP} deploy -a reconcilerio-ducks -n apps --wait-timeout 5m -y \
              -f https://github.com/reconcilerio/ducks/releases/download/v0.4.0/reconcilerio-ducks-v0.4.0.yaml
          echo "##[endgroup]"

          echo "##[group]Deploy reconcilerio-wa8s"
            kubectl create secret generic local-ca \
              --namespace wa8s-system \
              --type kubernetes.io/tls \
              --from-file ca.crt=${{ steps.registry.outputs.tls-ca }} \
              --from-literal tls.crt="" \
              --from-literal tls.key="" \
              --dry-run=client \
              -oyaml > ca.yaml

            # unindent to preserve whitespace
          cat << EOF > clusterrepository.yaml
          apiVersion: registries.wa8s.reconciler.io/v1alpha1
          kind: ClusterRepository
          metadata:
            name: external
          spec:
            template: ${{ steps.registry.outputs.registry }}/{{ .Kind }}/{{ .UID }}:{{ .ResourceVersion }}
          EOF

            ${KAPP} deploy -a reconcilerio-wa8s -n apps --wait-timeout 5m -y \
              -f <(${KBLD} -f bundle/.imgpkg/images.yml -f bundle/config/reconcilerio-wa8s.yaml) \
              -f bundle/kapp \
              -f ca.yaml \
              -f clusterrepository.yaml
          echo "##[endgroup]"

          echo "##[group]Deploy reconcilerio-wa8s-knative"
            ${KAPP} deploy -a reconcilerio-wa8s-knative -n apps --wait-timeout 5m -y \
              -f <(${KBLD} -f bundle/.imgpkg/images.yml -f bundle/config/reconcilerio-wa8s-knative.yaml) \
              -f bundle/kapp
          echo "##[endgroup]"

          echo "##[group]Deploy reconcilerio-wa8s-services"
            ${KAPP} deploy -a reconcilerio-wa8s-services -n apps --wait-timeout 5m -y \
              -f <(${KBLD} -f bundle/.imgpkg/images.yml -f bundle/config/reconcilerio-wa8s-services.yaml) \
              -f bundle/kapp
          echo "##[endgroup]"
      - name: Valkey service
        run: |
          set -o errexit
          set -o nounset
          set -o pipefail

          echo "##[group]kubectl apply -f examples/valkey-service/prereq/"
            kubectl apply -f examples/valkey-service/prereq/
            kubectl wait deployments.apps/valkey -n wa8s-service-valkey --for condition=available --timeout 1m
            kubectl wait serviceresourcedefinitions.services.wa8s.reconciler.io/valkey --for condition=ready --timeout 5m
          echo "##[endgroup]"

          echo "##[group]kubectl apply -f examples/valkey-service/"
            kubectl apply -f examples/valkey-service/
            kubectl wait valkeys.x.services.wa8s.reconciler.io/my-valkey --for condition=ready --timeout 5m
            kubectl wait valkeyclients.x.services.wa8s.reconciler.io/my-valkey --for condition=ready --timeout 5m
            kubectl wait servicetrigger.knative.wa8s.reconciler.io/incrementor --for condition=ready --timeout 5m
          echo "##[endgroup]"

          echo "##[group]invoke incrementor"
            ingress_ip=$(kubectl get svc -n kourier-system kourier -o=jsonpath='{.status.loadBalancer.ingress[0].ip}')
            incrementor_host=$(kubectl get servicetriggers.knative.wa8s.reconciler.io incrementor -o=jsonpath='{.status.url}'| cut -d'/' -f3)

            count=$(curl -s -H "Host: ${incrementor_host}" http://${ingress_ip}/hello)
            if [ "${count}" == "1" ]; then
              echo "/hello count: ${count}"
            else
              echo "Unexpected /hello count: got ${count}, wanted 1"
              exit 1
            fi

            count=$(curl -s -H "Host: ${incrementor_host}" http://${ingress_ip}/greeting)
            if [ "${count}" == "1" ]; then
              echo "/greeting count: ${count}"
            else
              echo "Unexpected /greeting count: got ${count}, wanted 1"
              exit 1
            fi

            count=$(curl -s -H "Host: ${incrementor_host}" http://${ingress_ip}/hello)
            if [ "${count}" == "2" ]; then
              echo "/hello count: ${count}"
            else
              echo "Unexpected /hello count: got ${count}, wanted 2"
              exit 1
            fi

            count=$(curl -s -H "Host: ${incrementor_host}" http://${ingress_ip}/greeting)
            if [ "${count}" == "2" ]; then
              echo "/greeting count: ${count}"
            else
              echo "Unexpected /greeting count: got ${count}, wanted 2"
              exit 1
            fi
          echo "##[endgroup]"

      - name: Collect diagnostics
        run: ./.github/workflows/diagnostics.sh
        if: always()
        continue-on-error: true
      - name: kind logs
        uses: reconcilerio/kind/logs@v1
        with:
          artifact-name: kind-logs-${{ matrix.kubernetes }}-${{ matrix.os }}

      - name: Delete Gracefully
        run: |
          set -o errexit
          set -o nounset
          set -o pipefail

          echo "##[group]Delete Valkey service"
            kubectl delete -f examples/valkey-service/ --timeout 1m
            kubectl wait servicetrigger.knative.wa8s.reconciler.io/incrementor --for delete --timeout 5m
            kubectl wait valkeyclients.x.services.wa8s.reconciler.io/my-valkey --for delete --timeout 5m
            kubectl wait valkeys.x.services.wa8s.reconciler.io/my-valkey --for delete --timeout 5m
            
            kubectl delete -f examples/valkey-service/prereq/ --timeout 1m
            kubectl wait serviceresourcedefinitions.services.wa8s.reconciler.io/valkey --for delete --timeout 5m
            kubectl wait deployments.apps/valkey -n wa8s-service-valkey --for delete --timeout 1m
          echo "##[endgroup]"
          echo "##[group]Delete reconcilerio-wa8s-services"
            ${KAPP} delete -a reconcilerio-wa8s-services -n apps --wait-timeout 5m -y
          echo "##[endgroup]"
          echo "##[group]Delete reconcilerio-wa8s-knative"
            ${KAPP} delete -a reconcilerio-wa8s-knative -n apps --wait-timeout 5m -y
          echo "##[endgroup]"
          echo "##[group]Delete reconcilerio-wa8s"
            ${KAPP} delete -a reconcilerio-wa8s -n apps --wait-timeout 5m -y
          echo "##[endgroup]"
          echo "##[group]Delete reconcilerio-ducks"
            ${KAPP} delete -a reconcilerio-ducks -n apps --wait-timeout 5m -y
          echo "##[endgroup]"
          echo "##[group]Delete knative-serving"
            ${KAPP} delete -a knative-serving -n apps --wait-timeout 5m -y
          echo "##[endgroup]"
          echo "##[group]Delete cert-manager"
            ${KAPP} delete -a cert-manager -n apps --wait-timeout 5m -y
          echo "##[endgroup]"
        if: always()

      - name: Collect diagnostics (on delete failure)
        run: ./.github/workflows/diagnostics.sh
        if: failure()
        continue-on-error: true

      - name: Cleanup cluster
        run: kind delete cluster
        if: always()

  # aggregate the unit and acceptance results into a single job
  test:
    name: Test
    needs:
      - unit
      - acceptance
    if: ${{ !cancelled() && !failure() }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "it passed"

  release:
    name: Release
    if: startsWith(github.ref, 'refs/tags/')
    needs:
      - test
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v7
      - name: Restore GOTOOLCHAIN
        run: echo "GOTOOLCHAIN=local+auto" >> "${GITHUB_ENV}"
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Download staged bundle
        uses: actions/download-artifact@v8
        with:
          name: reconcilerio-wa8s-bundle.tar
      - parallel:
          - name: Install crane
            uses: reconcilerio/install-crane-action@v1
          - *install-kbld
          - *install-imgpkg
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Relocate bundle to public registry
        run: |
          set -o errexit
          set -o nounset
          set -o pipefail

          version=${{ steps.get_version.outputs.VERSION }}

          ${IMGPKG} copy --tar reconcilerio-wa8s-bundle.tar --to-repo "ghcr.io/${{ github.repository }}/bundle"
          crane tag "ghcr.io/${{ github.repository }}/bundle" "${version}"
          digest=$(crane digest "ghcr.io/${{ github.repository }}/bundle:${version}")

          scratch=$(mktemp -d -t bundle.XXXX)
          mkdir -p ${scratch}
          ${IMGPKG} pull -b "ghcr.io/${{ github.repository }}/bundle:${version}@${digest}" -o ${scratch}

          cp hack/boilerplate.yaml.txt reconcilerio-wa8s.yaml
          ${KBLD} -f ${scratch}/config/reconcilerio-wa8s.yaml -f ${scratch}/.imgpkg/images.yml \
            >> reconcilerio-wa8s.yaml

          cp hack/boilerplate.yaml.txt reconcilerio-wa8s-knative.yaml
          ${KBLD} -f ${scratch}/config/reconcilerio-wa8s-knative.yaml -f ${scratch}/.imgpkg/images.yml \
            >> reconcilerio-wa8s-knative.yaml

          cp hack/boilerplate.yaml.txt reconcilerio-wa8s-services.yaml
          ${KBLD} -f ${scratch}/config/reconcilerio-wa8s-services.yaml -f ${scratch}/.imgpkg/images.yml \
            >> reconcilerio-wa8s-services.yaml
      - name: Rename artifacts with version
        run: |
          set -o errexit
          set -o nounset
          set -o pipefail

          version=${{ steps.get_version.outputs.VERSION }}

          cp reconcilerio-wa8s-bundle.tar reconcilerio-wa8s-bundle-${version}.tar
          cp reconcilerio-wa8s.yaml reconcilerio-wa8s-${version}.yaml
          cp reconcilerio-wa8s-knative.yaml reconcilerio-wa8s-knative-${version}.yaml
          cp reconcilerio-wa8s-services.yaml reconcilerio-wa8s-services-${version}.yaml
      - name: Draft GitHub Release
        uses: softprops/action-gh-release@v3
        with:
          draft: true
          files: |
            reconcilerio-wa8s-bundle-${{ steps.get_version.outputs.VERSION }}.tar
            reconcilerio-wa8s-${{ steps.get_version.outputs.VERSION }}.yaml
            reconcilerio-wa8s-knative-${{ steps.get_version.outputs.VERSION }}.yaml
            reconcilerio-wa8s-services-${{ steps.get_version.outputs.VERSION }}.yaml
          fail_on_unmatched_files: true
          token: ${{ secrets.GITHUB_TOKEN }}
